import OOMP

OOMP.oompAddDetail(category="color",code="N",name="Brown",sort="00")
OOMP.oompAddDetail(category="color",code="R",name="Red",sort="01")
OOMP.oompAddDetail(category="color",code="O",name="Orange",sort="02")
OOMP.oompAddDetail(category="color",code="Y",name="Yellow",sort="03")
OOMP.oompAddDetail(category="color",code="G",name="Green",sort="04")
OOMP.oompAddDetail(category="color",code="L",name="Blue",sort="05")
OOMP.oompAddDetail(category="color",code="V",name="Purple",sort="06")
OOMP.oompAddDetail(category="color",code="E",name="Grey",sort="07")
OOMP.oompAddDetail(category="color",code="W",name="White",sort="08")
OOMP.oompAddDetail(category="color",code="B",name="Black",sort="09")
OOMP.oompAddDetail(category="color",code="P",name="Pink",sort="10")
OOMP.oompAddDetail(category="color",code="Z",name="Rainbow",sort="11")
OOMP.oompAddDetail(category="color",code="RGB",name="RGB",sort="12")
OOMP.oompAddDetail(category="color",code="GYR",name="Green, Yellow, Red",sort="12")
OOMP.oompAddDetail(category="color",code="C",name="Clear",sort="12")
OOMP.oompAddDetail(category="color",code="X",name="")
OOMP.oompAddDetail(category="color",code="U",name="")
OOMP.oompAddDetail(category="color",code="T",name="")
OOMP.oompAddDetail(category="color",code="M",name="Metal")
OOMP.oompAddDetail(category="color",code="I9",name="IR (940 nm)")
