import OOMP

OOMP.oompAddDetail(category="type",code="ANTE",name="Antenna")
OOMP.oompAddDetail(category="type",code="BAHO",name="Battery Holder")
OOMP.oompAddDetail(category="type",code="BAPI",name="Badge Pin")
OOMP.oompAddDetail(category="type",code="BREB",name="Breadboard")
OOMP.oompAddDetail(category="type",code="BUTA",name="Pushbutton (Tactile)")
OOMP.oompAddDetail(category="type",code="BUTP",name="Pushbutton")
OOMP.oompAddDetail(category="type",code="BUZZ",name="Buzzer")
OOMP.oompAddDetail(category="type",code="CABL",name="Cable")
OOMP.oompAddDetail(category="type",code="CAPC",name="Capacitor (Ceramic)")
OOMP.oompAddDetail(category="type",code="CAPE",name="Capacitor (Electrolytic)")
OOMP.oompAddDetail(category="type",code="CAPT",name="Capacitor (Tantalum)")
OOMP.oompAddDetail(category="type",code="CERE",name="Ceramic Resonator")
OOMP.oompAddDetail(category="type",code="DBCO",name="Connector")
OOMP.oompAddDetail(category="type",code="CRHO",name="Crimp Housing")
OOMP.oompAddDetail(category="type",code="DCJP",name="DC Jack")
OOMP.oompAddDetail(category="type",code="DIOD",name="Diode")
OOMP.oompAddDetail(category="type",code="DIOS",name="Diode (Schottky)")
OOMP.oompAddDetail(category="type",code="DISP",name="Display")
OOMP.oompAddDetail(category="type",code="FERB",name="Ferrite Bead")
OOMP.oompAddDetail(category="type",code="HEAD",name="Header")
OOMP.oompAddDetail(category="type",code="HEAF",name="Female Header")
OOMP.oompAddDetail(category="type",code="HEAL",name="Header (Long)")
OOMP.oompAddDetail(category="type",code="HEDS",name="Headphone Socket")
OOMP.oompAddDetail(category="type",code="HELF",name="Female Header (Long)")
OOMP.oompAddDetail(category="type",code="HESH",name="Heat Shrink")
OOMP.oompAddDetail(category="type",code="ICIC",name="")
OOMP.oompAddDetail(category="type",code="MCUU",name="MCU")
OOMP.oompAddDetail(category="type",code="ICSO",name="IC Socket")
OOMP.oompAddDetail(category="type",code="INDU",name="Inductor")
OOMP.oompAddDetail(category="type",code="JSTS",name="JST Socket")
OOMP.oompAddDetail(category="type",code="JUMP",name="Jumper")
OOMP.oompAddDetail(category="type",code="LEDS",name="LED")
OOMP.oompAddDetail(category="type",code="MICR",name="Microphone")
OOMP.oompAddDetail(category="type",code="MOSN",name="N-Ch. MOSFET")
OOMP.oompAddDetail(category="type",code="MOSP",name="P-Ch. MOSFET")
OOMP.oompAddDetail(category="type",code="MOTO",name="Motor")
OOMP.oompAddDetail(category="type",code="NHFF",name="Nylon Standoff (F-F)")
OOMP.oompAddDetail(category="type",code="NNUT",name="Nylon Nut")
OOMP.oompAddDetail(category="type",code="NSCR",name="Nylon Screw")
OOMP.oompAddDetail(category="type",code="NUTT",name="Nut")
OOMP.oompAddDetail(category="type",code="OPAM",name="Op Amp")
OOMP.oompAddDetail(category="type",code="PHTR",name="Phototransistor")
OOMP.oompAddDetail(category="type",code="POTE",name="Potentiometer")
OOMP.oompAddDetail(category="type",code="POAD",name="Power Adapter")
OOMP.oompAddDetail(category="type",code="PRIV",name="Plastic Rivet")
OOMP.oompAddDetail(category="type",code="RBCC",name="Crimped Ribbon Cable")
OOMP.oompAddDetail(category="type",code="REFU",name="Resetable Fuse")
OOMP.oompAddDetail(category="type",code="RELA",name="Relay")
OOMP.oompAddDetail(category="type",code="RESA",name="Resistor Array")
OOMP.oompAddDetail(category="type",code="RESE",name="Resistor")
OOMP.oompAddDetail(category="type",code="RJ45",name="RJ45")
OOMP.oompAddDetail(category="type",code="SCRE",name="Machine Screw")
OOMP.oompAddDetail(category="type",code="SDCS",name="SD Card Socket")
OOMP.oompAddDetail(category="type",code="SENS",name="Sensor")
OOMP.oompAddDetail(category="type",code="SWIS",name="Switch (Slide)")
OOMP.oompAddDetail(category="type",code="TERS",name="Screw Terminal")
OOMP.oompAddDetail(category="type",code="THER",name="Thermistor")
OOMP.oompAddDetail(category="type",code="TILS",name="Tilt Switch")
OOMP.oompAddDetail(category="type",code="TRNN",name="NPN Transistor")
OOMP.oompAddDetail(category="type",code="TRNP",name="PNP Transistor")
OOMP.oompAddDetail(category="type",code="USBS",name="USB Socket")
OOMP.oompAddDetail(category="type",code="UFLS",name="UFL Socket")
OOMP.oompAddDetail(category="type",code="VARI",name="Varistor")
OOMP.oompAddDetail(category="type",code="VREG",name="Voltage Regulator")
OOMP.oompAddDetail(category="type",code="WIRS",name="Stranded Wire")
OOMP.oompAddDetail(category="type",code="XTAL",name="Crystal")
