import OOMP

OOMP.oompAddDetail(category="size",code="0402",name="SMD (0402)")
OOMP.oompAddDetail(category="size",code="0603",name="SMD (0603)")
OOMP.oompAddDetail(category="size",code="06038",name="SMD (0603-8)")
OOMP.oompAddDetail(category="size",code="0805",name="SMD (0805)")
OOMP.oompAddDetail(category="size",code="0806",name="SMD (0806)")
OOMP.oompAddDetail(category="size",code="1206",name="SMD (1206)")
OOMP.oompAddDetail(category="size",code="1263",name="SMD (1206-3)")
OOMP.oompAddDetail(category="size",code="1210",name="SMD (1210)")
OOMP.oompAddDetail(category="size",code="1812",name="SMD (1812)")
OOMP.oompAddDetail(category="size",code="1268",name="SMD (1206-8)")
OOMP.oompAddDetail(category="size",code="2312",name="SMD (2312)")
OOMP.oompAddDetail(category="size",code="2917",name="SMD (2917)")
OOMP.oompAddDetail(category="size",code="D214",name="SMD (DO-214)")
OOMP.oompAddDetail(category="size",code="MMA",name="SMD (Mini MELF)")
OOMP.oompAddDetail(category="size",code="3025",name="SMD (3025)")
OOMP.oompAddDetail(category="size",code="1515",name="SMD (1515)")
OOMP.oompAddDetail(category="size",code="2020",name="SMD (2020)")
OOMP.oompAddDetail(category="size",code="2121",name="SMD (2121)")
OOMP.oompAddDetail(category="size",code="3215",name="SMD (3215)")
OOMP.oompAddDetail(category="size",code="3216",name="SMD (3216)")
OOMP.oompAddDetail(category="size",code="3528",name="SMD (3528)")
OOMP.oompAddDetail(category="size",code="3535",name="SMD (3535)")
OOMP.oompAddDetail(category="size",code="3643",name="SMD (3643)")
OOMP.oompAddDetail(category="size",code="4628",name="SMD (4628)")
OOMP.oompAddDetail(category="size",code="4632",name="SMD (4632)")
OOMP.oompAddDetail(category="size",code="4735",name="SMD (4735)")
OOMP.oompAddDetail(category="size",code="5032",name="SMD (5032)")
OOMP.oompAddDetail(category="size",code="5050",name="SMD (5050)")
OOMP.oompAddDetail(category="size",code="5252",name="SMD (5252)")
OOMP.oompAddDetail(category="size",code="6032",name="SMD (6032)")
OOMP.oompAddDetail(category="size",code="6060",name="SMD (6060)")
OOMP.oompAddDetail(category="size",code="6727",name="SMD (6727)")
OOMP.oompAddDetail(category="size",code="7135",name="SMD (7135)")
OOMP.oompAddDetail(category="size",code="7343",name="SMD (7343)")
OOMP.oompAddDetail(category="size",code="7827",name="SMD (7827)")
OOMP.oompAddDetail(category="size",code="AVA",name="SMD (AVX-A)")
OOMP.oompAddDetail(category="size",code="AVB",name="SMD (AVX-B)")
OOMP.oompAddDetail(category="size",code="AVC",name="SMD (AVX-C)")
OOMP.oompAddDetail(category="size",code="S123",name="SMD (SOD-123)")
OOMP.oompAddDetail(category="size",code="S323",name="SMD (SOD-323)")
OOMP.oompAddDetail(category="size",code="SO123",name="SMD (SOT-123)")
OOMP.oompAddDetail(category="size",code="SO223",name="SMD (SOT-223)")
OOMP.oompAddDetail(category="size",code="SO323",name="SMD (SOT-323)")
OOMP.oompAddDetail(category="size",code="SO363",name="SMD (SOT-363)")
OOMP.oompAddDetail(category="size",code="SO23",name="SMD (SOT-23)")
OOMP.oompAddDetail(category="size",code="SO23F",name="SMD (SOT-23F)")
OOMP.oompAddDetail(category="size",code="SC8",name="8 Pin SMD (SOIC)")
OOMP.oompAddDetail(category="size",code="SC14",name="14 Pin SMD (SOIC)")
OOMP.oompAddDetail(category="size",code="SC16",name="16 Pin SMD (SOIC)")
OOMP.oompAddDetail(category="size",code="SC16W",name="16 Pin SMD (SOIC Wide)")
OOMP.oompAddDetail(category="size",code="SC75",name="5 Pin SMD (SC70)")
OOMP.oompAddDetail(category="size",code="PS20",name="SMD (Power SO-20)")
OOMP.oompAddDetail(category="size",code="DFN8",name="SMD (DFN-8)")
OOMP.oompAddDetail(category="size",code="DFN10",name="SMD (DFN-10)")
OOMP.oompAddDetail(category="size",code="UDF6",name="SMD (UDFN-6)")
OOMP.oompAddDetail(category="size",code="SO235",name="SMD (SOT-23-5)")
OOMP.oompAddDetail(category="size",code="SO236",name="SMD (SOT-23-6)")
OOMP.oompAddDetail(category="size",code="SO238",name="SMD (SOT-23-8)")
OOMP.oompAddDetail(category="size",code="SO89",name="SMD (SOT-89)")
OOMP.oompAddDetail(category="size",code="T92",name="TO-92")
OOMP.oompAddDetail(category="size",code="T220",name="TO-220")
OOMP.oompAddDetail(category="size",code="T252",name="TO-252")
OOMP.oompAddDetail(category="size",code="G28",name="28 AWG")
OOMP.oompAddDetail(category="size",code="P400",name="400 Point")
OOMP.oompAddDetail(category="size",code="P170",name="170 Point")
OOMP.oompAddDetail(category="size",code="CR1220",name="CR1220")
OOMP.oompAddDetail(category="size",code="P830",name="830 Point")
OOMP.oompAddDetail(category="size",code="W04",name="1/4 Watt")
OOMP.oompAddDetail(category="size",code="W08",name="1/8 Watt")
OOMP.oompAddDetail(category="size",code="W1",name="1 Watt")
OOMP.oompAddDetail(category="size",code="W2",name="2 Watt")
OOMP.oompAddDetail(category="size",code="W3",name="3 Watt")
OOMP.oompAddDetail(category="size",code="W4",name="4 Watt")
OOMP.oompAddDetail(category="size",code="W5",name="5 Watt")
OOMP.oompAddDetail(category="size",code="W6",name="6 Watt")
OOMP.oompAddDetail(category="size",code="W7",name="7 Watt")
OOMP.oompAddDetail(category="size",code="W8",name="8 Watt")
OOMP.oompAddDetail(category="size",code="W9",name="9 Watt")
OOMP.oompAddDetail(category="size",code="W10",name="10 Watt")
OOMP.oompAddDetail(category="size",code="W11",name="11 Watt")
OOMP.oompAddDetail(category="size",code="W12",name="12 Watt")
OOMP.oompAddDetail(category="size",code="W13",name="13 Watt")
OOMP.oompAddDetail(category="size",code="W14",name="14 Watt")
OOMP.oompAddDetail(category="size",code="W15",name="15 Watt")
OOMP.oompAddDetail(category="size",code="W16",name="16 Watt")
OOMP.oompAddDetail(category="size",code="W17",name="17 Watt")
OOMP.oompAddDetail(category="size",code="W18",name="18 Watt")
OOMP.oompAddDetail(category="size",code="W19",name="19 Watt")
OOMP.oompAddDetail(category="size",code="W20",name="20 Watt")
OOMP.oompAddDetail(category="size",code="W21",name="21 Watt")
OOMP.oompAddDetail(category="size",code="W22",name="22 Watt")
OOMP.oompAddDetail(category="size",code="W23",name="23 Watt")
OOMP.oompAddDetail(category="size",code="W24",name="24 Watt")
OOMP.oompAddDetail(category="size",code="W25",name="25 Watt")
OOMP.oompAddDetail(category="size",code="W26",name="26 Watt")
OOMP.oompAddDetail(category="size",code="W27",name="27 Watt")
OOMP.oompAddDetail(category="size",code="W28",name="28 Watt")
OOMP.oompAddDetail(category="size",code="W29",name="29 Watt")
OOMP.oompAddDetail(category="size",code="W30",name="30 Watt")
OOMP.oompAddDetail(category="size",code="W31",name="31 Watt")
OOMP.oompAddDetail(category="size",code="W32",name="32 Watt")
OOMP.oompAddDetail(category="size",code="W33",name="33 Watt")
OOMP.oompAddDetail(category="size",code="W34",name="34 Watt")
OOMP.oompAddDetail(category="size",code="W35",name="35 Watt")
OOMP.oompAddDetail(category="size",code="W36",name="36 Watt")
OOMP.oompAddDetail(category="size",code="W37",name="37 Watt")
OOMP.oompAddDetail(category="size",code="W38",name="38 Watt")
OOMP.oompAddDetail(category="size",code="W39",name="39 Watt")
OOMP.oompAddDetail(category="size",code="W40",name="40 Watt")
OOMP.oompAddDetail(category="size",code="W41",name="41 Watt")
OOMP.oompAddDetail(category="size",code="W42",name="42 Watt")
OOMP.oompAddDetail(category="size",code="W43",name="43 Watt")
OOMP.oompAddDetail(category="size",code="W44",name="44 Watt")
OOMP.oompAddDetail(category="size",code="W45",name="45 Watt")
OOMP.oompAddDetail(category="size",code="W46",name="46 Watt")
OOMP.oompAddDetail(category="size",code="W47",name="47 Watt")
OOMP.oompAddDetail(category="size",code="W48",name="48 Watt")
OOMP.oompAddDetail(category="size",code="W49",name="49 Watt")
OOMP.oompAddDetail(category="size",code="W50",name="50 Watt")
OOMP.oompAddDetail(category="size",code="W51",name="51 Watt")
OOMP.oompAddDetail(category="size",code="W52",name="52 Watt")
OOMP.oompAddDetail(category="size",code="W53",name="53 Watt")
OOMP.oompAddDetail(category="size",code="W54",name="54 Watt")
OOMP.oompAddDetail(category="size",code="W55",name="55 Watt")
OOMP.oompAddDetail(category="size",code="W56",name="56 Watt")
OOMP.oompAddDetail(category="size",code="W57",name="57 Watt")
OOMP.oompAddDetail(category="size",code="W58",name="58 Watt")
OOMP.oompAddDetail(category="size",code="W59",name="59 Watt")
OOMP.oompAddDetail(category="size",code="W60",name="60 Watt")
OOMP.oompAddDetail(category="size",code="W61",name="61 Watt")
OOMP.oompAddDetail(category="size",code="W62",name="62 Watt")
OOMP.oompAddDetail(category="size",code="W63",name="63 Watt")
OOMP.oompAddDetail(category="size",code="W64",name="64 Watt")
OOMP.oompAddDetail(category="size",code="W65",name="65 Watt")
OOMP.oompAddDetail(category="size",code="W66",name="66 Watt")
OOMP.oompAddDetail(category="size",code="W67",name="67 Watt")
OOMP.oompAddDetail(category="size",code="W68",name="68 Watt")
OOMP.oompAddDetail(category="size",code="W69",name="69 Watt")
OOMP.oompAddDetail(category="size",code="W70",name="70 Watt")
OOMP.oompAddDetail(category="size",code="W71",name="71 Watt")
OOMP.oompAddDetail(category="size",code="W72",name="72 Watt")
OOMP.oompAddDetail(category="size",code="W73",name="73 Watt")
OOMP.oompAddDetail(category="size",code="W74",name="74 Watt")
OOMP.oompAddDetail(category="size",code="W75",name="75 Watt")
OOMP.oompAddDetail(category="size",code="W76",name="76 Watt")
OOMP.oompAddDetail(category="size",code="W77",name="77 Watt")
OOMP.oompAddDetail(category="size",code="W78",name="78 Watt")
OOMP.oompAddDetail(category="size",code="W79",name="79 Watt")
OOMP.oompAddDetail(category="size",code="W80",name="80 Watt")
OOMP.oompAddDetail(category="size",code="W81",name="81 Watt")
OOMP.oompAddDetail(category="size",code="W82",name="82 Watt")
OOMP.oompAddDetail(category="size",code="W83",name="83 Watt")
OOMP.oompAddDetail(category="size",code="W84",name="84 Watt")
OOMP.oompAddDetail(category="size",code="W85",name="85 Watt")
OOMP.oompAddDetail(category="size",code="W86",name="86 Watt")
OOMP.oompAddDetail(category="size",code="W87",name="87 Watt")
OOMP.oompAddDetail(category="size",code="W88",name="88 Watt")
OOMP.oompAddDetail(category="size",code="W89",name="89 Watt")
OOMP.oompAddDetail(category="size",code="W90",name="90 Watt")
OOMP.oompAddDetail(category="size",code="W91",name="91 Watt")
OOMP.oompAddDetail(category="size",code="W92",name="92 Watt")
OOMP.oompAddDetail(category="size",code="W93",name="93 Watt")
OOMP.oompAddDetail(category="size",code="W94",name="94 Watt")
OOMP.oompAddDetail(category="size",code="W95",name="95 Watt")
OOMP.oompAddDetail(category="size",code="W96",name="96 Watt")
OOMP.oompAddDetail(category="size",code="W97",name="97 Watt")
OOMP.oompAddDetail(category="size",code="W98",name="98 Watt")
OOMP.oompAddDetail(category="size",code="W99",name="99 Watt")
OOMP.oompAddDetail(category="size",code="TH",name="")
OOMP.oompAddDetail(category="size",code="SM",name="")
OOMP.oompAddDetail(category="size",code="ST",name="Standard")
OOMP.oompAddDetail(category="size",code="MC",name="Micro")
OOMP.oompAddDetail(category="size",code="MN",name="Mini")
OOMP.oompAddDetail(category="size",code="TA",name="Type A")
OOMP.oompAddDetail(category="size",code="TB",name="Type B")
OOMP.oompAddDetail(category="size",code="SC",name="Solid")
OOMP.oompAddDetail(category="size",code="01D",name="0.1 mm")
OOMP.oompAddDetail(category="size",code="02D",name="0.2 mm")
OOMP.oompAddDetail(category="size",code="03D",name="0.3 mm")
OOMP.oompAddDetail(category="size",code="04D",name="0.4 mm")
OOMP.oompAddDetail(category="size",code="05D",name="0.5 mm")
OOMP.oompAddDetail(category="size",code="06D",name="0.6 mm")
OOMP.oompAddDetail(category="size",code="07D",name="0.7 mm")
OOMP.oompAddDetail(category="size",code="08D",name="0.8 mm")
OOMP.oompAddDetail(category="size",code="09D",name="0.9 mm")
OOMP.oompAddDetail(category="size",code="10D",name="1 mm")
OOMP.oompAddDetail(category="size",code="11D",name="1.1 mm")
OOMP.oompAddDetail(category="size",code="12D",name="1.2 mm")
OOMP.oompAddDetail(category="size",code="13D",name="1.3 mm")
OOMP.oompAddDetail(category="size",code="14D",name="1.4 mm")
OOMP.oompAddDetail(category="size",code="15D",name="1.5 mm")
OOMP.oompAddDetail(category="size",code="16D",name="1.6 mm")
OOMP.oompAddDetail(category="size",code="17D",name="1.7 mm")
OOMP.oompAddDetail(category="size",code="175D",name="1.75 mm")
OOMP.oompAddDetail(category="size",code="18D",name="1.8 mm")
OOMP.oompAddDetail(category="size",code="19D",name="1.9 mm")
OOMP.oompAddDetail(category="size",code="20D",name="2 mm")
OOMP.oompAddDetail(category="size",code="21D",name="2.1 mm")
OOMP.oompAddDetail(category="size",code="22D",name="2.2 mm")
OOMP.oompAddDetail(category="size",code="23D",name="2.3 mm")
OOMP.oompAddDetail(category="size",code="24D",name="2.4 mm")
OOMP.oompAddDetail(category="size",code="25D",name="2.5 mm")
OOMP.oompAddDetail(category="size",code="26D",name="2.6 mm")
OOMP.oompAddDetail(category="size",code="27D",name="2.7 mm")
OOMP.oompAddDetail(category="size",code="28D",name="2.8 mm")
OOMP.oompAddDetail(category="size",code="29D",name="2.9 mm")
OOMP.oompAddDetail(category="size",code="30D",name="3.0 mm")
OOMP.oompAddDetail(category="size",code="35D",name="3.5 mm")
OOMP.oompAddDetail(category="size",code="36D",name="3.6 mm")
OOMP.oompAddDetail(category="size",code="45D",name="4.5 mm")
OOMP.oompAddDetail(category="size",code="55D",name="5.5 mm")
OOMP.oompAddDetail(category="size",code="63D",name="6.3 mm")
OOMP.oompAddDetail(category="size",code="81D",name="8.1 mm")
OOMP.oompAddDetail(category="size",code="I05D",name="1.27 mm")
OOMP.oompAddDetail(category="size",code="I01",name="2.54 mm")
OOMP.oompAddDetail(category="size",code="I02",name="5.08 mm")
OOMP.oompAddDetail(category="size",code="I03",name="7.62 mm")
OOMP.oompAddDetail(category="size",code="I04",name="10.16 mm")
OOMP.oompAddDetail(category="size",code="I05",name="12.7 mm")
OOMP.oompAddDetail(category="size",code="I06",name="15.24 mm")
OOMP.oompAddDetail(category="size",code="I07",name="17.78 mm")
OOMP.oompAddDetail(category="size",code="I08",name="20.32 mm")
OOMP.oompAddDetail(category="size",code="I09",name="22.86 mm")
OOMP.oompAddDetail(category="size",code="01",name="1 mm")
OOMP.oompAddDetail(category="size",code="02",name="2 mm")
OOMP.oompAddDetail(category="size",code="03",name="3 mm")
OOMP.oompAddDetail(category="size",code="39D",name="3.9 mm")
OOMP.oompAddDetail(category="size",code="04",name="4 mm")
OOMP.oompAddDetail(category="size",code="05",name="5 mm")
OOMP.oompAddDetail(category="size",code="52D",name="5.2 mm")
OOMP.oompAddDetail(category="size",code="06",name="6 mm")
OOMP.oompAddDetail(category="size",code="S63D",name="SMD (6.3 mm)")
OOMP.oompAddDetail(category="size",code="65D",name="6.5 mm")
OOMP.oompAddDetail(category="size",code="07",name="7 mm")
OOMP.oompAddDetail(category="size",code="S21D",name="2.1 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S05",name="5 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S06",name="6 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S07",name="7 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S08",name="8 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S09",name="9 mm (SMD)")
OOMP.oompAddDetail(category="size",code="S10",name="10 mm (SMD)")
OOMP.oompAddDetail(category="size",code="08",name="8 mm")
OOMP.oompAddDetail(category="size",code="88D",name="8.8 mm")
OOMP.oompAddDetail(category="size",code="09",name="9 mm")
OOMP.oompAddDetail(category="size",code="92D",name="9.2 mm")
OOMP.oompAddDetail(category="size",code="95D",name="9.5 mm")
OOMP.oompAddDetail(category="size",code="97D",name="9.7 mm")
OOMP.oompAddDetail(category="size",code="98D",name="9.8 mm")
OOMP.oompAddDetail(category="size",code="10",name="10 mm")
OOMP.oompAddDetail(category="size",code="11",name="11 mm")
OOMP.oompAddDetail(category="size",code="12",name="12 mm")
OOMP.oompAddDetail(category="size",code="13",name="13 mm")
OOMP.oompAddDetail(category="size",code="14",name="14 mm")
OOMP.oompAddDetail(category="size",code="15",name="15 mm")
OOMP.oompAddDetail(category="size",code="155D",name="15.5 mm")
OOMP.oompAddDetail(category="size",code="16",name="16 mm")
OOMP.oompAddDetail(category="size",code="17",name="17 mm")
OOMP.oompAddDetail(category="size",code="18",name="18 mm")
OOMP.oompAddDetail(category="size",code="19",name="19 mm")
OOMP.oompAddDetail(category="size",code="64DX49S",name="6.4 x 4.9 mm")
OOMP.oompAddDetail(category="size",code="81DX42S",name="8.1 x 4.2 mm")
OOMP.oompAddDetail(category="size",code="87DX45D",name="8.7 mm x 4.5 mm")
OOMP.oompAddDetail(category="size",code="19X15",name="19 x 15 mm")
OOMP.oompAddDetail(category="size",code="25X13",name="25 x 13 mm")
OOMP.oompAddDetail(category="size",code="20",name="20 mm")
OOMP.oompAddDetail(category="size",code="21",name="21 mm")
OOMP.oompAddDetail(category="size",code="22",name="22 mm")
OOMP.oompAddDetail(category="size",code="23",name="23 mm")
OOMP.oompAddDetail(category="size",code="24",name="24 mm")
OOMP.oompAddDetail(category="size",code="25",name="25 mm")
OOMP.oompAddDetail(category="size",code="26",name="26 mm")
OOMP.oompAddDetail(category="size",code="27",name="27 mm")
OOMP.oompAddDetail(category="size",code="28",name="28 mm")
OOMP.oompAddDetail(category="size",code="29",name="29 mm")
OOMP.oompAddDetail(category="size",code="30",name="30 mm")
OOMP.oompAddDetail(category="size",code="31",name="31 mm")
OOMP.oompAddDetail(category="size",code="32",name="32 mm")
OOMP.oompAddDetail(category="size",code="33",name="33 mm")
OOMP.oompAddDetail(category="size",code="34",name="34 mm")
OOMP.oompAddDetail(category="size",code="35",name="35 mm")
OOMP.oompAddDetail(category="size",code="36",name="36 mm")
OOMP.oompAddDetail(category="size",code="37",name="37 mm")
OOMP.oompAddDetail(category="size",code="38",name="38 mm")
OOMP.oompAddDetail(category="size",code="39",name="39 mm")
OOMP.oompAddDetail(category="size",code="40",name="40 mm")
OOMP.oompAddDetail(category="size",code="41",name="41 mm")
OOMP.oompAddDetail(category="size",code="42",name="42 mm")
OOMP.oompAddDetail(category="size",code="43",name="43 mm")
OOMP.oompAddDetail(category="size",code="44",name="44 mm")
OOMP.oompAddDetail(category="size",code="45",name="45 mm")
OOMP.oompAddDetail(category="size",code="46",name="46 mm")
OOMP.oompAddDetail(category="size",code="47",name="47 mm")
OOMP.oompAddDetail(category="size",code="48",name="48 mm")
OOMP.oompAddDetail(category="size",code="49",name="49 mm")
OOMP.oompAddDetail(category="size",code="50",name="50 mm")
OOMP.oompAddDetail(category="size",code="51",name="51 mm")
OOMP.oompAddDetail(category="size",code="52",name="52 mm")
OOMP.oompAddDetail(category="size",code="53",name="53 mm")
OOMP.oompAddDetail(category="size",code="54",name="54 mm")
OOMP.oompAddDetail(category="size",code="55",name="55 mm")
OOMP.oompAddDetail(category="size",code="56",name="56 mm")
OOMP.oompAddDetail(category="size",code="57",name="57 mm")
OOMP.oompAddDetail(category="size",code="58",name="58 mm")
OOMP.oompAddDetail(category="size",code="59",name="59 mm")
OOMP.oompAddDetail(category="size",code="60",name="60 mm")
OOMP.oompAddDetail(category="size",code="61",name="61 mm")
OOMP.oompAddDetail(category="size",code="62",name="62 mm")
OOMP.oompAddDetail(category="size",code="63",name="63 mm")
OOMP.oompAddDetail(category="size",code="64",name="64 mm")
OOMP.oompAddDetail(category="size",code="65",name="65 mm")
OOMP.oompAddDetail(category="size",code="66",name="66 mm")
OOMP.oompAddDetail(category="size",code="67",name="67 mm")
OOMP.oompAddDetail(category="size",code="68",name="68 mm")
OOMP.oompAddDetail(category="size",code="69",name="69 mm")
OOMP.oompAddDetail(category="size",code="70",name="70 mm")
OOMP.oompAddDetail(category="size",code="71",name="71 mm")
OOMP.oompAddDetail(category="size",code="72",name="72 mm")
OOMP.oompAddDetail(category="size",code="73",name="73 mm")
OOMP.oompAddDetail(category="size",code="74",name="74 mm")
OOMP.oompAddDetail(category="size",code="75",name="75 mm")
OOMP.oompAddDetail(category="size",code="76",name="76 mm")
OOMP.oompAddDetail(category="size",code="77",name="77 mm")
OOMP.oompAddDetail(category="size",code="78",name="78 mm")
OOMP.oompAddDetail(category="size",code="79",name="79 mm")
OOMP.oompAddDetail(category="size",code="80",name="80 mm")
OOMP.oompAddDetail(category="size",code="81",name="81 mm")
OOMP.oompAddDetail(category="size",code="82",name="82 mm")
OOMP.oompAddDetail(category="size",code="83",name="83 mm")
OOMP.oompAddDetail(category="size",code="84",name="84 mm")
OOMP.oompAddDetail(category="size",code="85",name="85 mm")
OOMP.oompAddDetail(category="size",code="86",name="86 mm")
OOMP.oompAddDetail(category="size",code="87",name="87 mm")
OOMP.oompAddDetail(category="size",code="88",name="88 mm")
OOMP.oompAddDetail(category="size",code="89",name="89 mm")
OOMP.oompAddDetail(category="size",code="90",name="90 mm")
OOMP.oompAddDetail(category="size",code="91",name="91 mm")
OOMP.oompAddDetail(category="size",code="92",name="92 mm")
OOMP.oompAddDetail(category="size",code="93",name="93 mm")
OOMP.oompAddDetail(category="size",code="94",name="94 mm")
OOMP.oompAddDetail(category="size",code="95",name="95 mm")
OOMP.oompAddDetail(category="size",code="96",name="96 mm")
OOMP.oompAddDetail(category="size",code="97",name="97 mm")
OOMP.oompAddDetail(category="size",code="98",name="98 mm")
OOMP.oompAddDetail(category="size",code="99",name="99 mm")
OOMP.oompAddDetail(category="size",code="100",name="100 mm")
OOMP.oompAddDetail(category="size",code="101",name="101 mm")
OOMP.oompAddDetail(category="size",code="102",name="102 mm")
OOMP.oompAddDetail(category="size",code="103",name="103 mm")
OOMP.oompAddDetail(category="size",code="104",name="104 mm")
OOMP.oompAddDetail(category="size",code="105",name="105 mm")
OOMP.oompAddDetail(category="size",code="106",name="106 mm")
OOMP.oompAddDetail(category="size",code="107",name="107 mm")
OOMP.oompAddDetail(category="size",code="108",name="108 mm")
OOMP.oompAddDetail(category="size",code="109",name="109 mm")
OOMP.oompAddDetail(category="size",code="110",name="110 mm")
OOMP.oompAddDetail(category="size",code="111",name="111 mm")
OOMP.oompAddDetail(category="size",code="112",name="112 mm")
OOMP.oompAddDetail(category="size",code="113",name="113 mm")
OOMP.oompAddDetail(category="size",code="114",name="114 mm")
OOMP.oompAddDetail(category="size",code="115",name="115 mm")
OOMP.oompAddDetail(category="size",code="116",name="116 mm")
OOMP.oompAddDetail(category="size",code="117",name="117 mm")
OOMP.oompAddDetail(category="size",code="118",name="118 mm")
OOMP.oompAddDetail(category="size",code="119",name="119 mm")
OOMP.oompAddDetail(category="size",code="120",name="120 mm")
OOMP.oompAddDetail(category="size",code="121",name="121 mm")
OOMP.oompAddDetail(category="size",code="122",name="122 mm")
OOMP.oompAddDetail(category="size",code="123",name="123 mm")
OOMP.oompAddDetail(category="size",code="124",name="124 mm")
OOMP.oompAddDetail(category="size",code="125",name="125 mm")
OOMP.oompAddDetail(category="size",code="126",name="126 mm")
OOMP.oompAddDetail(category="size",code="127",name="127 mm")
OOMP.oompAddDetail(category="size",code="128",name="128 mm")
OOMP.oompAddDetail(category="size",code="129",name="129 mm")
OOMP.oompAddDetail(category="size",code="130",name="130 mm")
OOMP.oompAddDetail(category="size",code="131",name="131 mm")
OOMP.oompAddDetail(category="size",code="132",name="132 mm")
OOMP.oompAddDetail(category="size",code="133",name="133 mm")
OOMP.oompAddDetail(category="size",code="134",name="134 mm")
OOMP.oompAddDetail(category="size",code="135",name="135 mm")
OOMP.oompAddDetail(category="size",code="136",name="136 mm")
OOMP.oompAddDetail(category="size",code="137",name="137 mm")
OOMP.oompAddDetail(category="size",code="138",name="138 mm")
OOMP.oompAddDetail(category="size",code="139",name="139 mm")
OOMP.oompAddDetail(category="size",code="140",name="140 mm")
OOMP.oompAddDetail(category="size",code="141",name="141 mm")
OOMP.oompAddDetail(category="size",code="142",name="142 mm")
OOMP.oompAddDetail(category="size",code="143",name="143 mm")
OOMP.oompAddDetail(category="size",code="144",name="144 mm")
OOMP.oompAddDetail(category="size",code="145",name="145 mm")
OOMP.oompAddDetail(category="size",code="146",name="146 mm")
OOMP.oompAddDetail(category="size",code="147",name="147 mm")
OOMP.oompAddDetail(category="size",code="148",name="148 mm")
OOMP.oompAddDetail(category="size",code="149",name="149 mm")
OOMP.oompAddDetail(category="size",code="150",name="150 mm")
OOMP.oompAddDetail(category="size",code="151",name="151 mm")
OOMP.oompAddDetail(category="size",code="152",name="152 mm")
OOMP.oompAddDetail(category="size",code="153",name="153 mm")
OOMP.oompAddDetail(category="size",code="154",name="154 mm")
OOMP.oompAddDetail(category="size",code="155",name="155 mm")
OOMP.oompAddDetail(category="size",code="156",name="156 mm")
OOMP.oompAddDetail(category="size",code="157",name="157 mm")
OOMP.oompAddDetail(category="size",code="158",name="158 mm")
OOMP.oompAddDetail(category="size",code="159",name="159 mm")
OOMP.oompAddDetail(category="size",code="160",name="160 mm")
OOMP.oompAddDetail(category="size",code="161",name="161 mm")
OOMP.oompAddDetail(category="size",code="162",name="162 mm")
OOMP.oompAddDetail(category="size",code="163",name="163 mm")
OOMP.oompAddDetail(category="size",code="164",name="164 mm")
OOMP.oompAddDetail(category="size",code="165",name="165 mm")
OOMP.oompAddDetail(category="size",code="166",name="166 mm")
OOMP.oompAddDetail(category="size",code="167",name="167 mm")
OOMP.oompAddDetail(category="size",code="168",name="168 mm")
OOMP.oompAddDetail(category="size",code="169",name="169 mm")
OOMP.oompAddDetail(category="size",code="170",name="170 mm")
OOMP.oompAddDetail(category="size",code="171",name="171 mm")
OOMP.oompAddDetail(category="size",code="172",name="172 mm")
OOMP.oompAddDetail(category="size",code="173",name="173 mm")
OOMP.oompAddDetail(category="size",code="174",name="174 mm")
OOMP.oompAddDetail(category="size",code="175",name="175 mm")
OOMP.oompAddDetail(category="size",code="176",name="176 mm")
OOMP.oompAddDetail(category="size",code="177",name="177 mm")
OOMP.oompAddDetail(category="size",code="178",name="178 mm")
OOMP.oompAddDetail(category="size",code="179",name="179 mm")
OOMP.oompAddDetail(category="size",code="180",name="180 mm")
OOMP.oompAddDetail(category="size",code="181",name="181 mm")
OOMP.oompAddDetail(category="size",code="182",name="182 mm")
OOMP.oompAddDetail(category="size",code="183",name="183 mm")
OOMP.oompAddDetail(category="size",code="184",name="184 mm")
OOMP.oompAddDetail(category="size",code="185",name="185 mm")
OOMP.oompAddDetail(category="size",code="186",name="186 mm")
OOMP.oompAddDetail(category="size",code="187",name="187 mm")
OOMP.oompAddDetail(category="size",code="188",name="188 mm")
OOMP.oompAddDetail(category="size",code="189",name="189 mm")
OOMP.oompAddDetail(category="size",code="190",name="190 mm")
OOMP.oompAddDetail(category="size",code="191",name="191 mm")
OOMP.oompAddDetail(category="size",code="192",name="192 mm")
OOMP.oompAddDetail(category="size",code="193",name="193 mm")
OOMP.oompAddDetail(category="size",code="194",name="194 mm")
OOMP.oompAddDetail(category="size",code="195",name="195 mm")
OOMP.oompAddDetail(category="size",code="196",name="196 mm")
OOMP.oompAddDetail(category="size",code="197",name="197 mm")
OOMP.oompAddDetail(category="size",code="198",name="198 mm")
OOMP.oompAddDetail(category="size",code="199",name="199 mm")
OOMP.oompAddDetail(category="size",code="200",name="200 mm")
OOMP.oompAddDetail(category="size",code="201",name="201 mm")
OOMP.oompAddDetail(category="size",code="202",name="202 mm")
OOMP.oompAddDetail(category="size",code="203",name="203 mm")
OOMP.oompAddDetail(category="size",code="204",name="204 mm")
OOMP.oompAddDetail(category="size",code="205",name="205 mm")
OOMP.oompAddDetail(category="size",code="206",name="206 mm")
OOMP.oompAddDetail(category="size",code="207",name="207 mm")
OOMP.oompAddDetail(category="size",code="208",name="208 mm")
OOMP.oompAddDetail(category="size",code="209",name="209 mm")
OOMP.oompAddDetail(category="size",code="210",name="210 mm")
OOMP.oompAddDetail(category="size",code="211",name="211 mm")
OOMP.oompAddDetail(category="size",code="212",name="212 mm")
OOMP.oompAddDetail(category="size",code="213",name="213 mm")
OOMP.oompAddDetail(category="size",code="214",name="214 mm")
OOMP.oompAddDetail(category="size",code="215",name="215 mm")
OOMP.oompAddDetail(category="size",code="216",name="216 mm")
OOMP.oompAddDetail(category="size",code="217",name="217 mm")
OOMP.oompAddDetail(category="size",code="218",name="218 mm")
OOMP.oompAddDetail(category="size",code="219",name="219 mm")
OOMP.oompAddDetail(category="size",code="220",name="220 mm")
OOMP.oompAddDetail(category="size",code="221",name="221 mm")
OOMP.oompAddDetail(category="size",code="222",name="222 mm")
OOMP.oompAddDetail(category="size",code="223",name="223 mm")
OOMP.oompAddDetail(category="size",code="224",name="224 mm")
OOMP.oompAddDetail(category="size",code="225",name="225 mm")
OOMP.oompAddDetail(category="size",code="226",name="226 mm")
OOMP.oompAddDetail(category="size",code="227",name="227 mm")
OOMP.oompAddDetail(category="size",code="228",name="228 mm")
OOMP.oompAddDetail(category="size",code="229",name="229 mm")
OOMP.oompAddDetail(category="size",code="230",name="230 mm")
OOMP.oompAddDetail(category="size",code="231",name="231 mm")
OOMP.oompAddDetail(category="size",code="232",name="232 mm")
OOMP.oompAddDetail(category="size",code="233",name="233 mm")
OOMP.oompAddDetail(category="size",code="234",name="234 mm")
OOMP.oompAddDetail(category="size",code="235",name="235 mm")
OOMP.oompAddDetail(category="size",code="236",name="236 mm")
OOMP.oompAddDetail(category="size",code="237",name="237 mm")
OOMP.oompAddDetail(category="size",code="238",name="238 mm")
OOMP.oompAddDetail(category="size",code="239",name="239 mm")
OOMP.oompAddDetail(category="size",code="240",name="240 mm")
OOMP.oompAddDetail(category="size",code="241",name="241 mm")
OOMP.oompAddDetail(category="size",code="242",name="242 mm")
OOMP.oompAddDetail(category="size",code="243",name="243 mm")
OOMP.oompAddDetail(category="size",code="244",name="244 mm")
OOMP.oompAddDetail(category="size",code="245",name="245 mm")
OOMP.oompAddDetail(category="size",code="246",name="246 mm")
OOMP.oompAddDetail(category="size",code="247",name="247 mm")
OOMP.oompAddDetail(category="size",code="248",name="248 mm")
OOMP.oompAddDetail(category="size",code="249",name="249 mm")
OOMP.oompAddDetail(category="size",code="250",name="250 mm")
OOMP.oompAddDetail(category="size",code="1W",name="1 Wire")
OOMP.oompAddDetail(category="size",code="2W",name="2 Wire")
OOMP.oompAddDetail(category="size",code="3W",name="3 Wire")
OOMP.oompAddDetail(category="size",code="4W",name="4 Wire")
OOMP.oompAddDetail(category="size",code="5W",name="5 Wire")
OOMP.oompAddDetail(category="size",code="6W",name="6 Wire")
OOMP.oompAddDetail(category="size",code="7W",name="7 Wire")
OOMP.oompAddDetail(category="size",code="8W",name="8 Wire")
OOMP.oompAddDetail(category="size",code="9W",name="9 Wire")
OOMP.oompAddDetail(category="size",code="10W",name="10 Wire")
OOMP.oompAddDetail(category="size",code="11W",name="11 Wire")
OOMP.oompAddDetail(category="size",code="12W",name="12 Wire")
OOMP.oompAddDetail(category="size",code="13W",name="13 Wire")
OOMP.oompAddDetail(category="size",code="14W",name="14 Wire")
OOMP.oompAddDetail(category="size",code="15W",name="15 Wire")
OOMP.oompAddDetail(category="size",code="16W",name="16 Wire")
OOMP.oompAddDetail(category="size",code="17W",name="17 Wire")
OOMP.oompAddDetail(category="size",code="18W",name="18 Wire")
OOMP.oompAddDetail(category="size",code="19W",name="19 Wire")
OOMP.oompAddDetail(category="size",code="20W",name="20 Wire")
OOMP.oompAddDetail(category="size",code="21W",name="21 Wire")
OOMP.oompAddDetail(category="size",code="22W",name="22 Wire")
OOMP.oompAddDetail(category="size",code="23W",name="23 Wire")
OOMP.oompAddDetail(category="size",code="24W",name="24 Wire")
OOMP.oompAddDetail(category="size",code="25W",name="25 Wire")
OOMP.oompAddDetail(category="size",code="26W",name="26 Wire")
OOMP.oompAddDetail(category="size",code="27W",name="27 Wire")
OOMP.oompAddDetail(category="size",code="28W",name="28 Wire")
OOMP.oompAddDetail(category="size",code="29W",name="29 Wire")
OOMP.oompAddDetail(category="size",code="30W",name="30 Wire")
OOMP.oompAddDetail(category="size",code="31W",name="31 Wire")
OOMP.oompAddDetail(category="size",code="32W",name="32 Wire")
OOMP.oompAddDetail(category="size",code="33W",name="33 Wire")
OOMP.oompAddDetail(category="size",code="34W",name="34 Wire")
OOMP.oompAddDetail(category="size",code="35W",name="35 Wire")
OOMP.oompAddDetail(category="size",code="36W",name="36 Wire")
OOMP.oompAddDetail(category="size",code="37W",name="37 Wire")
OOMP.oompAddDetail(category="size",code="38W",name="38 Wire")
OOMP.oompAddDetail(category="size",code="39W",name="39 Wire")
OOMP.oompAddDetail(category="size",code="40W",name="40 Wire")
OOMP.oompAddDetail(category="size",code="41W",name="41 Wire")
OOMP.oompAddDetail(category="size",code="42W",name="42 Wire")
OOMP.oompAddDetail(category="size",code="43W",name="43 Wire")
OOMP.oompAddDetail(category="size",code="44W",name="44 Wire")
OOMP.oompAddDetail(category="size",code="45W",name="45 Wire")
OOMP.oompAddDetail(category="size",code="46W",name="46 Wire")
OOMP.oompAddDetail(category="size",code="47W",name="47 Wire")
OOMP.oompAddDetail(category="size",code="48W",name="48 Wire")
OOMP.oompAddDetail(category="size",code="49W",name="49 Wire")
OOMP.oompAddDetail(category="size",code="50W",name="50 Wire")
OOMP.oompAddDetail(category="size",code="51W",name="51 Wire")
OOMP.oompAddDetail(category="size",code="52W",name="52 Wire")
OOMP.oompAddDetail(category="size",code="53W",name="53 Wire")
OOMP.oompAddDetail(category="size",code="54W",name="54 Wire")
OOMP.oompAddDetail(category="size",code="55W",name="55 Wire")
OOMP.oompAddDetail(category="size",code="56W",name="56 Wire")
OOMP.oompAddDetail(category="size",code="57W",name="57 Wire")
OOMP.oompAddDetail(category="size",code="58W",name="58 Wire")
OOMP.oompAddDetail(category="size",code="59W",name="59 Wire")
OOMP.oompAddDetail(category="size",code="60W",name="60 Wire")
OOMP.oompAddDetail(category="size",code="61W",name="61 Wire")
OOMP.oompAddDetail(category="size",code="62W",name="62 Wire")
OOMP.oompAddDetail(category="size",code="63W",name="63 Wire")
OOMP.oompAddDetail(category="size",code="64W",name="64 Wire")
OOMP.oompAddDetail(category="size",code="65W",name="65 Wire")
OOMP.oompAddDetail(category="size",code="66W",name="66 Wire")
OOMP.oompAddDetail(category="size",code="67W",name="67 Wire")
OOMP.oompAddDetail(category="size",code="68W",name="68 Wire")
OOMP.oompAddDetail(category="size",code="69W",name="69 Wire")
OOMP.oompAddDetail(category="size",code="70W",name="70 Wire")
OOMP.oompAddDetail(category="size",code="71W",name="71 Wire")
OOMP.oompAddDetail(category="size",code="72W",name="72 Wire")
OOMP.oompAddDetail(category="size",code="73W",name="73 Wire")
OOMP.oompAddDetail(category="size",code="74W",name="74 Wire")
OOMP.oompAddDetail(category="size",code="75W",name="75 Wire")
OOMP.oompAddDetail(category="size",code="76W",name="76 Wire")
OOMP.oompAddDetail(category="size",code="77W",name="77 Wire")
OOMP.oompAddDetail(category="size",code="78W",name="78 Wire")
OOMP.oompAddDetail(category="size",code="79W",name="79 Wire")
OOMP.oompAddDetail(category="size",code="80W",name="80 Wire")
OOMP.oompAddDetail(category="size",code="81W",name="81 Wire")
OOMP.oompAddDetail(category="size",code="82W",name="82 Wire")
OOMP.oompAddDetail(category="size",code="83W",name="83 Wire")
OOMP.oompAddDetail(category="size",code="84W",name="84 Wire")
OOMP.oompAddDetail(category="size",code="85W",name="85 Wire")
OOMP.oompAddDetail(category="size",code="86W",name="86 Wire")
OOMP.oompAddDetail(category="size",code="87W",name="87 Wire")
OOMP.oompAddDetail(category="size",code="88W",name="88 Wire")
OOMP.oompAddDetail(category="size",code="89W",name="89 Wire")
OOMP.oompAddDetail(category="size",code="90W",name="90 Wire")
OOMP.oompAddDetail(category="size",code="91W",name="91 Wire")
OOMP.oompAddDetail(category="size",code="92W",name="92 Wire")
OOMP.oompAddDetail(category="size",code="93W",name="93 Wire")
OOMP.oompAddDetail(category="size",code="94W",name="94 Wire")
OOMP.oompAddDetail(category="size",code="95W",name="95 Wire")
OOMP.oompAddDetail(category="size",code="96W",name="96 Wire")
OOMP.oompAddDetail(category="size",code="97W",name="97 Wire")
OOMP.oompAddDetail(category="size",code="98W",name="98 Wire")
OOMP.oompAddDetail(category="size",code="99W",name="99 Wire")
OOMP.oompAddDetail(category="size",code="M1",name="M1")
OOMP.oompAddDetail(category="size",code="M2",name="M2")
OOMP.oompAddDetail(category="size",code="M3",name="M3")
OOMP.oompAddDetail(category="size",code="M4",name="M4")
OOMP.oompAddDetail(category="size",code="M5",name="M5")
OOMP.oompAddDetail(category="size",code="M6",name="M6")
OOMP.oompAddDetail(category="size",code="M7",name="M7")
OOMP.oompAddDetail(category="size",code="M8",name="M8")
OOMP.oompAddDetail(category="size",code="M9",name="M9")
OOMP.oompAddDetail(category="size",code="M10",name="M10")
OOMP.oompAddDetail(category="size",code="M12",name="M12")
OOMP.oompAddDetail(category="size",code="M15",name="M15")
OOMP.oompAddDetail(category="size",code="M20",name="M20")
OOMP.oompAddDetail(category="size",code="DI14",name="14 Pin DIP")
OOMP.oompAddDetail(category="size",code="DI16",name="16 Pin DIP")
OOMP.oompAddDetail(category="size",code="DI18",name="18 Pin DIP")
OOMP.oompAddDetail(category="size",code="DI28",name="28 Pin DIP")
OOMP.oompAddDetail(category="size",code="DI28W",name="28 Pin DIP (0.6\")")
OOMP.oompAddDetail(category="size",code="SS16",name="16 Pin SMD (SSOP)")
OOMP.oompAddDetail(category="size",code="SS24",name="24 Pin SMD (SSOP)")
OOMP.oompAddDetail(category="size",code="SS28",name="28 Pin SMD (SSOP)")
OOMP.oompAddDetail(category="size",code="SP08",name="8 Pin SMD (SOP)")
OOMP.oompAddDetail(category="size",code="SP16",name="16 Pin SMD (SOP)")
OOMP.oompAddDetail(category="size",code="SP20",name="20 Pin SMD (SOP)")
OOMP.oompAddDetail(category="size",code="MS08",name="8 Pin SMD (MSOP)")
OOMP.oompAddDetail(category="size",code="QFN16",name="16 Pin SMD (QFN)")
OOMP.oompAddDetail(category="size",code="QFN24",name="24 Pin SMD (QFN)")
OOMP.oompAddDetail(category="size",code="QFN28",name="28 Pin SMD (QFN)")
OOMP.oompAddDetail(category="size",code="QFN32",name="32 Pin SMD (QFN)")
OOMP.oompAddDetail(category="size",code="VQF32",name="32 Pin SMD (VQFN)")
OOMP.oompAddDetail(category="size",code="VQF44",name="44 Pin SMD (VQFN)")
OOMP.oompAddDetail(category="size",code="QFN48",name="48 Pin SMD (QFN)")
OOMP.oompAddDetail(category="size",code="HQFN33",name="33 Pin SMD (Heatsink QFN)")
OOMP.oompAddDetail(category="size",code="QFP32",name="32 Pin SMD (TQFP)")
OOMP.oompAddDetail(category="size",code="QFP64",name="64 Pin SMD (TQFP)")
OOMP.oompAddDetail(category="size",code="QFP44",name="44 Pin SMD (TQFP)")
OOMP.oompAddDetail(category="size",code="QFP100",name="100 Pin SMD (TQFP)")
OOMP.oompAddDetail(category="size",code="LG14",name="14 Pin SMD (LGA)")
OOMP.oompAddDetail(category="size",code="ML32",name="32 Pin SMD (MLF)")
OOMP.oompAddDetail(category="size",code="MLP28",name="28 Pin SMD (MLP)")
OOMP.oompAddDetail(category="size",code="TS14",name="14 Pin SMD (TSSOP)")
OOMP.oompAddDetail(category="size",code="TS20",name="20 Pin SMD (TSSOP)")
OOMP.oompAddDetail(category="size",code="TS24",name="24 Pin SMD (TSSOP)")
OOMP.oompAddDetail(category="size",code="128X64",name="128 x 64 Pixels")
OOMP.oompAddDetail(category="size",code="16X2",name="16 x 2 Character")
OOMP.oompAddDetail(category="size",code="7SEL",name="7 Segment LED")
OOMP.oompAddDetail(category="size",code="10SEL",name="10 Segment LED Bargraph")
OOMP.oompAddDetail(category="size",code="RJ45",name="128 x 64 Pixels")
OOMP.oompAddDetail(category="size",code="DB09",name="DB9")
OOMP.oompAddDetail(category="size",code="DB15",name="DB15")			
OOMP.oompAddDetail(category="size",code="DB25",name="DB25")
OOMP.oompAddDetail(category="size",code="ACUS",name="American Style (120v)")
OOMP.oompAddDetail(category="size",code="SMA",name="SMA")

######  LWH
"""
maxL = 200
maxW = 150
maxH = 20
for l in range(maxL):
    for w in range(maxW):
        for h in range(makH):
            #OOMP.oompAddDetail(category="size",code="L" + str(l) + "W" + str(w) + "H" + str(h),name="Length " + str(l) + "mm Width " + str(w) + "mm Height " + str(h) + " mm")
            OOMP.oompAddDetail(category="size",code="L" + str(l) + "W" + str(w) + "H" + str(h),name="" + str(l) + "mm x " + str(w) + "mm xt " + str(h) + " mm")
"""
OOMP.oompAddDetail(category="size",code="L169W130H18",name="169 mm x 130 mm x 18 mm")


OOMP.oompAddDetail(category="size",code="SZ130",name="130 Size")

######  More recent Additions
OOMP.oompAddDetail(category="size",code="XHP70",name="XHP 70")

######  Headers
OOMP.oompAddDetail(category="size",code="JSTXH",name="JST XH (2.5 mm)")

######  Companies for projects
OOMP.oompAddDetail(category="size",code="ADAF",name="Adafruit")
OOMP.oompAddDetail(category="size",code="ARDC",name="Compatible Arduino")
OOMP.oompAddDetail(category="size",code="ARDU",name="Arduino")
OOMP.oompAddDetail(category="size",code="OOML",name="Oomlout")
OOMP.oompAddDetail(category="size",code="RASP",name="Raspberry Pi Foundation")
OOMP.oompAddDetail(category="size",code="SEEE",name="SEEED Studios")
OOMP.oompAddDetail(category="size",code="SPAR",name="Sparkfun")

######  Panasonic Capacitors
OOMP.oompAddDetail(category="size",code="PANB",name="SMD (4 mm) (Panasonic B)")
OOMP.oompAddDetail(category="size",code="PANC",name="SMD (5 mm) (Panasonic C)")
OOMP.oompAddDetail(category="size",code="PAND",name="SMD (6.3 mm) (Panasonic D)")
OOMP.oompAddDetail(category="size",code="PAND8",name="SMD (6.3 mm) (Panasonic D8)")
OOMP.oompAddDetail(category="size",code="PANE",name="SMD (8 mm) (Panasonic E)")
OOMP.oompAddDetail(category="size",code="PANF",name="SMD (8 mm) (Panasonic F)")
OOMP.oompAddDetail(category="size",code="PANG",name="SMD (10 mm) (Panasonic G)")
