import OOMP

OOMP.oompAddDetail(category="index",code="67",name="1%")
OOMP.oompAddDetail(category="index",code="65",name="5%")
OOMP.oompAddDetail(category="index",code="68",name="Side Adjust")
OOMP.oompAddDetail(category="index",code="69",name="Panel Mount")
OOMP.oompAddDetail(category="index",code="70",name="Cross Head")
OOMP.oompAddDetail(category="index",code="80",name="Keyed")
OOMP.oompAddDetail(category="index",code="CA",name="Common Anode")
OOMP.oompAddDetail(category="index",code="CC",name="Common Cathode")
OOMP.oompAddDetail(category="index",code="LI",name="w/Lights")
OOMP.oompAddDetail(category="index",code="ML",name="Male")
OOMP.oompAddDetail(category="index",code="FM",name="Female")
OOMP.oompAddDetail(category="index",code="V6",name="6v")
OOMP.oompAddDetail(category="index",code="V63D",name="6.3v")
OOMP.oompAddDetail(category="index",code="V8",name="8v")
OOMP.oompAddDetail(category="index",code="V10",name="10v")
OOMP.oompAddDetail(category="index",code="V132D",name="13.2v")
OOMP.oompAddDetail(category="index",code="V16",name="16v")
OOMP.oompAddDetail(category="index",code="V3",name="3v")
OOMP.oompAddDetail(category="index",code="V5",name="5v")
OOMP.oompAddDetail(category="index",code="V33D",name="3.3v")
OOMP.oompAddDetail(category="index",code="V20",name="20v")
OOMP.oompAddDetail(category="index",code="V25",name="25v")
OOMP.oompAddDetail(category="index",code="V50",name="50v")
OOMP.oompAddDetail(category="index",code="V63",name="63v")
OOMP.oompAddDetail(category="index",code="V400",name="400v")
OOMP.oompAddDetail(category="index",code="V1000",name="1000v")
OOMP.oompAddDetail(category="index",code="V75",name="75v")
OOMP.oompAddDetail(category="index",code="V40",name="40v")
OOMP.oompAddDetail(category="index",code="AI",name="25 mA")
OOMP.oompAddDetail(category="index",code="AH",name="100 mA")
OOMP.oompAddDetail(category="index",code="AC",name="150 mA")
OOMP.oompAddDetail(category="index",code="AD",name="250 mA")
OOMP.oompAddDetail(category="index",code="AE",name="200 mA")
OOMP.oompAddDetail(category="index",code="A5D",name="500 mA")
OOMP.oompAddDetail(category="index",code="A1",name="1 A")
OOMP.oompAddDetail(category="index",code="AB",name="1.2 A")
OOMP.oompAddDetail(category="index",code="A2",name="2 A")
OOMP.oompAddDetail(category="index",code="A4",name="4 A")
OOMP.oompAddDetail(category="index",code="A5",name="5 A")
OOMP.oompAddDetail(category="index",code="SM",name="SMD")
OOMP.oompAddDetail(category="index",code="RA",name="Right Angle")
OOMP.oompAddDetail(category="index",code="RS",name="Right Angle (SMD)")
OOMP.oompAddDetail(category="index",code="SM",name="(SMD)")
OOMP.oompAddDetail(category="index",code="4P",name="(4 Pin)")
OOMP.oompAddDetail(category="index",code="RO",name="(Round)")
OOMP.oompAddDetail(category="index",code="I2",name="(I2C)")
OOMP.oompAddDetail(category="index",code="OOEB",name="(OOEB)")
OOMP.oompAddDetail(category="index",code="TH",name="(Through Hole)")
OOMP.oompAddDetail(category="index",code="LW",name="(Lead Wire)")
OOMP.oompAddDetail(category="index",code="WS2811",name="(WS2811)")
OOMP.oompAddDetail(category="index",code="TC3590",name="(3590)")

###### Project ones
